
# Don't use the Travis Container-Based Infrastructure
sudo: true

language: java

matrix:
  include:
    - os: linux
      dist: precise
      jdk: oraclejdk7
    - os: linux
      dist: precise
      jdk: oraclejdk8
    - os: linux
      dist: trusty
      jdk: oraclejdk9
      install: jdk_switcher use oraclejdk8 && ./gradlew wrapper --gradle-version=4.5 && jdk_switcher use oraclejdk9

script:
  - ./gradlew --version
  - ./gradlew -s clean build

