version: "{build}"

environment:
  TERM: dumb
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.7.0
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
    - JAVA_HOME: C:\Program Files\Java\jdk9
    - JAVA_HOME: C:\Program Files\Java\jdk10

install:
  - SET PATH=%JAVA_HOME%\bin;%PATH%
  - gradlew.bat --version

build_script:
  - gradlew.bat -u -i -S --no-daemon clean assemble

test_script:
  - gradlew.bat -u -i -S --no-daemon test

