
name: Build

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '.teamcity/**'
      - 'README.adoc'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
    name: Build and run tests - ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: |
            17
            8
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Build and run functional tests
        run: ./gradlew --show-version --full-stacktrace clean build
      - name: Upload reports
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: reports
          path: build/reports/**
          retention-days: 3
